"use client";

import type { ClinicConfig } from "@/types/site";
import { useLanguage } from "@/components/LanguageProvider";

export default function ClinicPrintReceipt({ config, booking, reference }: { config: ClinicConfig; booking: { name: string; service: string; doctor: string; date: string; time: string }; reference: string }) {
  const { t } = useLanguage();
  return <article id="appointment-receipt"><div className="receipt-card"><header className="receipt-header" style={{ backgroundColor: config.theme.primary }}><p style={{ margin: 0, fontSize: 12, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase" }}>{t("print.clinic.title", "Appointment receipt")}</p><h1 style={{ margin: "8px 0 0", fontSize: 26 }}>{config.siteName}</h1><p style={{ margin: "6px 0 0", opacity: .86 }}>{config.contact.address}</p></header><div className="receipt-body"><p style={{ margin: "0 0 20px", fontSize: 15 }}>{t("print.requestReceived", "Request received")} · {t("print.reference", "Reference")} <strong>{reference}</strong></p><div className="receipt-grid"><div><p className="receipt-label">{t("print.patient", "Patient")}</p><p className="receipt-value">{booking.name}</p></div><div><p className="receipt-label">{t("print.treatment", "Treatment")}</p><p className="receipt-value">{booking.service}</p></div><div><p className="receipt-label">{t("print.dentist", "Preferred dentist")}</p><p className="receipt-value">{booking.doctor}</p></div><div><p className="receipt-label">{t("print.requestedDate", "Requested date")}</p><p className="receipt-value">{booking.date}</p></div><div><p className="receipt-label">{t("print.requestedTime", "Requested time")}</p><p className="receipt-value">{booking.time}</p></div><div><p className="receipt-label">{t("print.status", "Status")}</p><p className="receipt-value">{t("print.pendingConfirmation", "Pending confirmation")}</p></div></div><footer className="receipt-footer">{t("print.clinic.note", "This is a request receipt, not a confirmed appointment. Our team will contact you via WhatsApp to confirm your visit.")}<br />{config.contact.hours}</footer></div></div></article>;
}
