"use client";

import type { HotelConfig } from "@/types/site";
import { useLanguage } from "@/components/LanguageProvider";

export default function HotelPrintVoucher({ config, enquiry, reference }: { config: HotelConfig; enquiry: Record<string, string>; reference: string }) {
  const { t } = useLanguage();
  return <article id="hotel-voucher-receipt"><div className="receipt-card"><header className="receipt-header" style={{ backgroundColor: config.theme.primary }}><p style={{ margin: 0, fontSize: 12, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase" }}>{t("print.hotel.title", "Stay enquiry voucher")}</p><h1 style={{ margin: "8px 0 0", fontSize: 26 }}>{config.siteName}</h1><p style={{ margin: "6px 0 0", opacity: .86 }}>{config.contact.address}</p></header><div className="receipt-body"><p style={{ margin: "0 0 20px", fontSize: 15 }}>{t("print.enquiryReceived", "Enquiry received")} · {t("print.reference", "Reference")} <strong>{reference}</strong></p><div className="receipt-grid"><div><p className="receipt-label">{t("print.guest", "Guest")}</p><p className="receipt-value">{enquiry.name}</p></div><div><p className="receipt-label">{t("print.roomPreference", "Room preference")}</p><p className="receipt-value">{enquiry.room}</p></div><div><p className="receipt-label">{t("print.checkIn", "Check-in")}</p><p className="receipt-value">{enquiry.checkIn}</p></div><div><p className="receipt-label">{t("print.checkOut", "Check-out")}</p><p className="receipt-value">{enquiry.checkOut}</p></div><div><p className="receipt-label">{t("print.guests", "Guests")}</p><p className="receipt-value">{enquiry.guests}</p></div><div><p className="receipt-label">{t("print.status", "Status")}</p><p className="receipt-value">{t("print.pendingAvailability", "Pending availability")}</p></div></div><footer className="receipt-footer">{t("print.hotel.note", "This is an availability enquiry, not a confirmed stay. Our reservations team will contact you to confirm availability and your final rate in LKR.")}<br />{config.contact.hours}</footer></div></div></article>;
}
