export type Language = "en" | "si" | "ta";

export const languageNames: Record<Language, string> = {
  en: "English",
  si: "සිංහල",
  ta: "தமிழ்",
};

const translations: Record<Exclude<Language, "en">, Record<string, string>> = {
  si: {
    "common.addressLabel": "අප වෙත පැමිණෙන්න", "common.hoursLabel": "විවෘත වේලාවන්", "common.themeToggle": "තේමාව මාරු කරන්න", "common.openMenu": "මෙනුව විවෘත කරන්න", "common.closeMenu": "මෙනුව වසන්න",
    "nav.Home": "මුල් පිටුව", "nav.Services": "සේවා", "nav.Doctors": "වෛද්‍යවරු", "nav.Gallery": "ගැලරිය", "nav.Contact": "අමතන්න", "nav.Book now": "දැන් වෙන්කරන්න",
    "nav.Rooms & rates": "කාමර සහ මිල", "nav.Experiences": "අත්දැකීම්", "nav.Enquire": "විමසන්න", "nav.Menu": "මෙනුව", "nav.Catering": "ආහාර සැපයීම", "nav.Reserve": "වෙන්කරන්න",
    "clinic.hero.title": "ඔබේ සිනහවට නිසි සැලකිල්ල", "clinic.hero.subtitle": "Negombo පවුල් සඳහා වසර 12ක විශ්වාසදායක දන්ත සත්කාරය. මිනිත්තුවකින් වෙන්කරන්න.",
    "clinic.hero.cta": "හමුවීමක් වෙන්කරන්න", "clinic.labels.servicesTitle": "සේවා සහ පැහැදිලි මිල ගණන්", "clinic.labels.bookingTitle": "හමුවීමක් වෙන්කරන්න",
    "clinic.labels.nameLabel": "සම්පූර්ණ නම", "clinic.labels.phoneLabel": "දුරකථන අංකය", "clinic.labels.serviceLabel": "ප්‍රතිකාරය", "clinic.labels.servicePlaceholder": "ප්‍රතිකාරයක් තෝරන්න", "clinic.labels.doctorLabel": "කැමති දන්ත වෛද්‍යවරයා", "clinic.labels.doctorPlaceholder": "වෛද්‍යවරයෙකු තෝරන්න", "clinic.labels.dateLabel": "කැමති දිනය", "clinic.labels.timeLabel": "කැමති වේලාව", "clinic.labels.submitLabel": "හමුවීමේ ඉල්ලීම තහවුරු කරන්න",
    "clinic.labels.confirmationTitle": "හමුවීමේ ඉල්ලීම ලැබුණි", "clinic.labels.confirmationMessage": "WhatsApp හරහා ඉක්මනින් තහවුරු කරන්නෙමු.", "clinic.labels.bookingDetailsTitle": "ඔබේ හමුවීමේ විස්තර",
    "clinic.labels.doctorsEyebrow": "ඔබේ දන්ත සත්කාර කණ්ඩායම", "clinic.labels.doctorsTitle": "උණුසුම් සහ විශේෂඥ සත්කාරය", "clinic.labels.doctorsDescription": "අපගේ වෛද්‍යවරු සවන් දී, විකල්ප පැහැදිලි කර, සෑම හමුවීමක්ම පහසු කරති.",
    "clinic.labels.galleryEyebrow": "වඩා විශ්වාසදායක සිනහවක්", "clinic.labels.galleryTitle": "සිතාබලා කළ සත්කාරයේ වෙනස බලන්න", "clinic.labels.comparisonBeforeLabel": "පෙර", "clinic.labels.comparisonAfterLabel": "පසු", "clinic.labels.comparisonControlLabel": "ප්‍රතිකාරයට පෙර සහ පසු සසඳන්න",
    "clinic.labels.contactEyebrow": "සායනය සොයාගන්න", "clinic.labels.contactTitle": "Negombo හි පහසු දන්ත සත්කාරය", "clinic.labels.contactWhatsAppLabel": "WhatsApp හරහා කතා කරන්න", "clinic.labels.addressLabel": "අප වෙත පැමිණෙන්න", "clinic.labels.hoursLabel": "විවෘත වේලාවන්",
    "clinic.service.cleaning": "දත් පිරිසිදු කිරීම සහ ඔප දැමීම", "clinic.service.filling": "දත් පිරවීම", "clinic.service.root-canal": "දත් මුල් ඇළ ප්‍රතිකාරය", "clinic.service.extraction": "දත් ඉවත් කිරීම", "clinic.service.whitening": "දත් සුදු කිරීම",
    "hotel.hero.title": "වඩා නිහඬ විවේකයක්.", "hotel.hero.subtitle": "මුහුදට අවදි වී, තටාකය අසල රැඳී, දකුණු ශ්‍රී ලංකාව ඔබේම කරගන්න.", "hotel.hero.cta": "ලබාගත හැකිදැයි බලන්න",
    "hotel.labels.roomsEyebrow": "ඔබේ ආකාරයට නවාතැන්", "hotel.labels.roomsTitle": "සෙමින් ගත කරන උදෑසන සඳහා කාමර", "hotel.labels.availabilityTitle": "ඔබේ නවාතැන සැලසුම් කරන්න", "hotel.labels.directBookingMessage": "සෘජුව වෙන්කරන්න, අමතර කොමිස් වළකින්න.",
    "hotel.labels.checkInLabel": "පැමිණීම", "hotel.labels.checkOutLabel": "පිටවීම", "hotel.labels.guestsLabel": "අමුත්තන්", "hotel.labels.roomLabel": "කාමර තේරීම", "hotel.labels.roomPlaceholder": "කාමරයක් තෝරන්න", "hotel.labels.enquirySubmitLabel": "ලබාගත හැකිදැයි විමසන්න",
    "hotel.room.ocean-suite": "සාගර කට්ටලය", "hotel.room.garden-suite": "උද්‍යාන කට්ටලය", "hotel.room.family-pavilion": "පවුල් නිවස", "hotel.labels.attractionsEyebrow": "විලාට එහා", "hotel.labels.attractionsTitle": "ඔබේ වේගයට දකුණ", "hotel.labels.currencyLabel": "පෙන්වන මුදල්", "hotel.labels.roomsRateSuffix": "රාත්‍රියකට", "hotel.labels.indicativeRateLabel": "ආසන්න පරිවර්තනයකි. අවසන් මිල LKR වලින් තහවුරු කෙරේ.", "hotel.labels.confirmationTitle": "ලබාගත හැකිදැයි විමසීම ලැබුණි", "hotel.labels.confirmationWhatsAppLabel": "WhatsApp හරහා යවන්න", "hotel.labels.printVoucherLabel": "වවුචරය මුද්‍රණය කරන්න", "hotel.labels.enquiryNameLabel": "සම්පූර්ණ නම", "hotel.labels.enquiryPhoneLabel": "දුරකථන අංකය",
    "restaurant.hero.title": "තවත් රසවත් ශ්‍රී ලාංකික ආහාර.", "restaurant.hero.subtitle": "තද දූපත් රස, කාලීන අමුද්‍රව්‍ය සහ මේසය වටා දිගු සන්ධ්‍යා.", "restaurant.hero.cta": "මෙනුව බලන්න",
    "restaurant.labels.menuEyebrow": "මෙනුව", "restaurant.labels.menuTitle": "අදහසක් සහිත රස", "restaurant.labels.menuAllLabel": "සියල්ල", "restaurant.labels.orderTitle": "ඔබේ ඇණවුම", "restaurant.labels.orderEmptyLabel": "ආරම්භ කිරීමට රසවත් දෙයක් එක් කරන්න.", "restaurant.labels.orderTotalLabel": "එකතුව", "restaurant.labels.orderWhatsAppLabel": "WhatsApp හරහා ඇණවුම් කරන්න", "restaurant.labels.cateringTitle": "මතකයේ රැඳෙන උත්සව සඳහා ආහාර සැපයීම", "restaurant.labels.reservationTitle": "මේසයක් වෙන්කරන්න",
  },
  ta: {
    "common.addressLabel": "எங்களைப் பார்வையிடுங்கள்", "common.hoursLabel": "திறந்திருக்கும் நேரம்", "common.themeToggle": "தீம் மாற்று", "common.openMenu": "மெனுவைத் திறக்கவும்", "common.closeMenu": "மெனுவை மூடவும்",
    "nav.Home": "முகப்பு", "nav.Services": "சேவைகள்", "nav.Doctors": "மருத்துவர்கள்", "nav.Gallery": "படத்தொகுப்பு", "nav.Contact": "தொடர்பு", "nav.Book now": "இப்போது பதிவு", "nav.Rooms & rates": "அறைகள் மற்றும் விலைகள்", "nav.Experiences": "அனுபவங்கள்", "nav.Enquire": "விசாரிக்க", "nav.Menu": "மெனு", "nav.Catering": "உணவு வழங்கல்", "nav.Reserve": "முன்பதிவு",
    "clinic.hero.title": "உங்கள் புன்னகையை அக்கறையுடன் கவனிப்போம்", "clinic.hero.subtitle": "Negombo குடும்பங்களுக்கு 12 ஆண்டுகளாக நம்பகமான பல் பராமரிப்பு. ஒரு நிமிடத்தில் பதிவு செய்யுங்கள்.", "clinic.hero.cta": "சந்திப்பை பதிவு செய்யுங்கள்", "clinic.labels.servicesTitle": "சேவைகள் மற்றும் தெளிவான விலைகள்", "clinic.labels.bookingTitle": "சந்திப்பை பதிவு செய்யுங்கள்",
    "clinic.labels.nameLabel": "முழு பெயர்", "clinic.labels.phoneLabel": "தொலைபேசி எண்", "clinic.labels.serviceLabel": "சிகிச்சை", "clinic.labels.servicePlaceholder": "சிகிச்சையைத் தேர்ந்தெடுக்கவும்", "clinic.labels.doctorLabel": "விருப்பமான பல் மருத்துவர்", "clinic.labels.doctorPlaceholder": "மருத்துவரைத் தேர்ந்தெடுக்கவும்", "clinic.labels.dateLabel": "விருப்பமான தேதி", "clinic.labels.timeLabel": "விருப்பமான நேரம்", "clinic.labels.submitLabel": "சந்திப்பு கோரிக்கையை உறுதிப்படுத்தவும்",
    "clinic.labels.confirmationTitle": "சந்திப்பு கோரிக்கை பெறப்பட்டது", "clinic.labels.confirmationMessage": "WhatsApp மூலம் விரைவில் உறுதிப்படுத்துவோம்.", "clinic.labels.bookingDetailsTitle": "உங்கள் சந்திப்பு விவரங்கள்", "clinic.labels.doctorsEyebrow": "உங்கள் பல் பராமரிப்பு குழு", "clinic.labels.doctorsTitle": "அன்பான நிபுணத்துவ பராமரிப்பு", "clinic.labels.galleryEyebrow": "அதிக நம்பிக்கையான புன்னகை", "clinic.labels.galleryTitle": "கவனமான பராமரிப்பின் வித்தியாசத்தைப் பாருங்கள்", "clinic.labels.comparisonBeforeLabel": "முன்", "clinic.labels.comparisonAfterLabel": "பின்", "clinic.labels.comparisonControlLabel": "சிகிச்சைக்கு முன் மற்றும் பின் ஒப்பிடுக", "clinic.labels.contactEyebrow": "மருத்துவமனையைக் கண்டறியுங்கள்", "clinic.labels.contactTitle": "Negombo-வில் வசதியான பராமரிப்பு", "clinic.labels.contactWhatsAppLabel": "WhatsApp-ல் பேசுங்கள்", "clinic.labels.addressLabel": "எங்களைப் பார்வையிடுங்கள்", "clinic.labels.hoursLabel": "திறந்திருக்கும் நேரம்",
    "clinic.service.cleaning": "பற்கள் சுத்தம் மற்றும் மெருகூட்டல்", "clinic.service.filling": "பல் நிரப்புதல்", "clinic.service.root-canal": "வேர் கால்வாய் சிகிச்சை", "clinic.service.extraction": "பல் அகற்றுதல்", "clinic.service.whitening": "பற்கள் வெண்மையாக்குதல்",
    "hotel.hero.title": "அமைதியான ஓய்வு.", "hotel.hero.subtitle": "கடலுடன் விழித்தெழுந்து, குளத்தின் அருகில் ஓய்வெடுத்து, தெற்கு இலங்கையை உங்களுடையதாக்குங்கள்.", "hotel.hero.cta": "கிடைப்பைச் சரிபார்க்கவும்", "hotel.labels.roomsEyebrow": "உங்கள் தங்குமுறை", "hotel.labels.roomsTitle": "மெதுவான காலைகளுக்கான அறைகள்", "hotel.labels.availabilityTitle": "உங்கள் தங்குமுறையைத் திட்டமிடுங்கள்", "hotel.labels.directBookingMessage": "நேரடியாக பதிவு செய்து, கமிஷனைத் தவிர்க்கவும்.", "hotel.labels.checkInLabel": "வருகை", "hotel.labels.checkOutLabel": "புறப்பாடு", "hotel.labels.guestsLabel": "விருந்தினர்கள்", "hotel.labels.roomLabel": "அறை விருப்பம்", "hotel.labels.roomPlaceholder": "அறையைத் தேர்ந்தெடுக்கவும்", "hotel.labels.enquirySubmitLabel": "கிடைப்பைப் பற்றி விசாரிக்கவும்",
    "hotel.room.ocean-suite": "கடல் காட்சி அறை", "hotel.room.garden-suite": "தோட்ட அறை", "hotel.room.family-pavilion": "குடும்ப அறை", "hotel.labels.attractionsEyebrow": "வில்லாவிற்கு அப்பால்", "hotel.labels.attractionsTitle": "உங்கள் வேகத்தில் தெற்கு", "hotel.labels.currencyLabel": "காட்சி நாணயம்", "hotel.labels.roomsRateSuffix": "ஒரு இரவுக்கு", "hotel.labels.indicativeRateLabel": "குறிப்புக்கான மாற்று. இறுதி விலை LKR-ல் உறுதி செய்யப்படும்.", "hotel.labels.confirmationTitle": "கிடைப்புக் கோரிக்கை பெறப்பட்டது", "hotel.labels.confirmationWhatsAppLabel": "WhatsApp மூலம் அனுப்பவும்", "hotel.labels.printVoucherLabel": "வவுச்சரை அச்சிடவும்", "hotel.labels.enquiryNameLabel": "முழு பெயர்", "hotel.labels.enquiryPhoneLabel": "தொலைபேசி எண்",
    "restaurant.hero.title": "இலங்கை உணவு, இன்னும் கொஞ்சம் தீவிரத்துடன்.", "restaurant.hero.subtitle": "தீவு சுவைகள், பருவகால பொருட்கள் மற்றும் மேசையைச் சுற்றிய நீண்ட மாலைகள்.", "restaurant.hero.cta": "மெனுவைப் பாருங்கள்", "restaurant.labels.menuEyebrow": "மெனு", "restaurant.labels.menuTitle": "கருத்துடன் கூடிய சுவை", "restaurant.labels.menuAllLabel": "அனைத்தும்", "restaurant.labels.orderTitle": "உங்கள் ஆர்டர்", "restaurant.labels.orderEmptyLabel": "தொடங்க சுவையான ஒன்றைச் சேர்க்கவும்.", "restaurant.labels.orderTotalLabel": "மொத்தம்", "restaurant.labels.orderWhatsAppLabel": "WhatsApp மூலம் ஆர்டர்", "restaurant.labels.cateringTitle": "நினைவில் நிற்கும் நிகழ்வுகளுக்கான உணவு வழங்கல்", "restaurant.labels.reservationTitle": "மேசையை முன்பதிவு செய்யுங்கள்",
    "restaurant.menu.chicken-kottu": "கோழி கொத்து", "restaurant.menu.jackfruit-curry": "பலாப்பழக் கறி", "restaurant.menu.prawn-curry": "இறால் கறி", "restaurant.menu.egg-hoppers": "முட்டை ஆப்பம்", "restaurant.menu.watalappan": "வத்தலப்பன்", "restaurant.menu.lime-juice": "மசாலா எலுமிச்சை சோடா",
  },
};

export function translate(language: Language, key: string, fallback: string): string {
  return language === "en" ? fallback : translations[language][key] || fallback;
}
