import type { ClinicConfig } from "@/types/site";

export const clinicConfig = {
  id: "clinic",
  siteName: "Sunshine Dental Clinic",
  tagline: "Negombo",
  theme: {
    primary: "#0F6E56",
    primaryDark: "#085041",
    font: "system-ui, sans-serif",
    logoText: "Sunshine Dental",
    logoImage: "/images/logos/sunshine-dental-logo.png",
  },
  hero: {
    title: "Your smile, looked after properly",
    subtitle: "12 years serving Negombo families. Book in under a minute.",
    cta: "Book an appointment",
    image: "/images/clinic/hero.webp",
  },
  trustSignals: [
    { label: "Years in practice", value: "12" },
    { label: "Patients treated", value: "8,400+" },
    { label: "Qualified dentists", value: "3" },
  ],
  services: [
    { id: "cleaning", name: "Teeth cleaning & polish", priceLKR: 3500, duration: "30 min" },
    { id: "filling", name: "Tooth filling (composite)", priceLKR: 6500, duration: "45 min" },
    { id: "root-canal", name: "Root canal treatment", priceLKR: 18000, duration: "90 min" },
    { id: "extraction", name: "Tooth extraction", priceLKR: 4500, duration: "30 min" },
    { id: "whitening", name: "Teeth whitening", priceLKR: 22000, duration: "60 min" },
  ],
  doctors: [
    {
      name: "Dr. Nadeesha Perera",
      qualification: "BDS (Colombo)",
      specialty: "General & cosmetic dentistry",
      bio: "Known for calm, considered care and a gentle approach with nervous patients.",
      photo: "/images/clinic/dr-nadeesha.webp",
    },
    {
      name: "Dr. Ashan Fernando",
      qualification: "BDS, MSc Orthodontics",
      specialty: "Orthodontics & smile design",
      bio: "Focused on confident, long-lasting smiles through thoughtful treatment planning.",
      photo: "/images/clinic/dr-ashan.webp",
    },
  ],
  gallery: [
    { src: "/images/clinic/hero.webp", alt: "Sunlit treatment room at Sunshine Dental Clinic" },
    { src: "/images/clinic/dr-nadeesha.webp", alt: "A Sunshine Dental Clinic dentist in a consultation room" },
    { src: "/images/clinic/dr-ashan.webp", alt: "A Sunshine Dental Clinic orthodontist in a consultation room" },
  ],
  beforeAfter: {
    beforeImage: "/images/clinic/smile-before.webp",
    afterImage: "/images/clinic/smile-after.webp",
    disclaimer: "Illustrative cosmetic dentistry outcome. Individual treatment results vary.",
  },
  contact: {
    address: "142 Poruthota Road, Negombo",
    hours: "Monday–Saturday, 8:00 AM–6:00 PM",
    mapEmbedUrl: "https://www.google.com/maps?q=Negombo%2C%20Sri%20Lanka&output=embed",
  },
  whatsapp: {
    number: "94771234567",
    defaultMessage: "Hi, I would like to book a dental appointment.",
    ariaLabel: "Start a WhatsApp chat with Sunshine Dental Clinic",
  },
  navigation: [
    { label: "Home", href: "#home" },
    { label: "Services", href: "#services" },
    { label: "Doctors", href: "#doctors" },
    { label: "Gallery", href: "#gallery" },
    { label: "Contact", href: "#contact" },
    { label: "Book now", href: "#booking" },
  ],
  labels: {
    servicesTitle: "Services & transparent pricing",
    bookingTitle: "Book an appointment",
    nameLabel: "Full name",
    phoneLabel: "Phone number",
    serviceLabel: "Treatment",
    servicePlaceholder: "Select a treatment",
    doctorLabel: "Preferred dentist",
    doctorPlaceholder: "Select a dentist",
    dateLabel: "Preferred date",
    timeLabel: "Preferred time",
    submitLabel: "Confirm appointment request",
    confirmationTitle: "Appointment request received",
    confirmationReference: "Your reference number is {reference}.",
    confirmationMessage: "We will confirm your appointment shortly via WhatsApp.",
    themeToggleLabel: "Switch color theme",
    menuLabel: "Open navigation menu",
    closeMenuLabel: "Close navigation menu",
    footerHeading: "Care that fits your life",
    footerDescription: "Friendly, modern dental care for the whole family in Negombo.",
    addressLabel: "Visit us",
    hoursLabel: "Opening hours",
    copyright: "Sunshine Dental Clinic. Demo site.",
    doctorsEyebrow: "Meet your dental team",
    doctorsTitle: "Expert care, without the clinical coldness",
    doctorsDescription: "Our dentists take time to listen, explain your options, and make every visit feel straightforward.",
    contactEyebrow: "Find the clinic",
    contactTitle: "Convenient care, right in Negombo",
    mapTitle: "Map showing the Sunshine Dental Clinic area in Negombo",
    contactWhatsAppLabel: "Chat on WhatsApp",
    galleryEyebrow: "A more confident smile",
    galleryTitle: "See the difference thoughtful care can make",
    comparisonBeforeLabel: "Before",
    comparisonAfterLabel: "After",
    comparisonControlLabel: "Drag to compare before and after treatment",
    printConfirmationLabel: "Print confirmation",
    confirmationWhatsAppLabel: "Send details on WhatsApp",
    bookingDetailsTitle: "Your appointment details",
    requestedDateLabel: "Requested date",
    requestedTimeLabel: "Requested time",
    confirmationWhatsAppMessage: "Hello Sunshine Dental Clinic, I would like to confirm appointment {reference}. Patient: {name}. Treatment: {service}. Dentist: {doctor}. Date: {date}. Time: {time}.",
  },
  bookingReferencePrefix: "SDC",
} satisfies ClinicConfig;
