import type { HotelConfig } from "@/types/site";

export const hotelConfig = {
  id: "hotel",
  siteName: "Kahanda Cove",
  tagline: "A private coastal villa in Galle",
  theme: {
    primary: "#8A4B2A",
    primaryDark: "#60311B",
    font: "Georgia, 'Times New Roman', serif",
    logoText: "Kahanda Cove",
  },
  hero: {
    title: "A quieter kind of escape.",
    subtitle: "Wake to the ocean, linger by the pool, and make southern Sri Lanka your own.",
    cta: "Check availability",
    image: "/images/hotel/hero.webp",
  },
  navigation: [
    { label: "Home", href: "#home" },
    { label: "Rooms & rates", href: "#rooms" },
    { label: "Experiences", href: "#experiences" },
    { label: "Enquire", href: "#availability" },
  ],
  rooms: [
    { id: "ocean-suite", name: "Ocean Suite", description: "A generous king suite with a private terrace and uninterrupted sea views.", guests: "2 guests", rateLKR: 68000, amenities: ["King bed", "Ocean terrace", "Breakfast included"], image: "/images/hotel/suite.webp" },
    { id: "garden-suite", name: "Garden Suite", description: "Quiet tropical views, a reading corner, and an indoor-outdoor rain shower.", guests: "2 guests", rateLKR: 52000, amenities: ["King bed", "Garden view", "Rain shower"], image: "/images/hotel/suite.webp" },
    { id: "family-pavilion", name: "Family Pavilion", description: "Two connecting bedrooms for unhurried family stays by the coast.", guests: "4 guests", rateLKR: 96000, amenities: ["2 bedrooms", "Private lounge", "Breakfast included"], image: "/images/hotel/suite.webp" },
  ],
  attractions: [
    { name: "Galle Fort", distance: "24 km · 40 min", description: "Wander colonial lanes, galleries, cafés and the sunset-facing ramparts." },
    { name: "Koggala Lake", distance: "12 km · 20 min", description: "A gentle boat ride among cinnamon islands and birdlife." },
    { name: "Weligama Bay", distance: "18 km · 30 min", description: "Easy surf, beachfront cafés and an unhurried morning swim." },
  ],
  exchangeRates: { LKR: 1, USD: 0.0033, EUR: 0.003, GBP: 0.0026 },
  contact: {
    address: "Talpe, Galle, Southern Province, Sri Lanka",
    hours: "Reservations: daily, 8:00 AM–8:00 PM",
    mapEmbedUrl: "https://www.google.com/maps?q=Talpe%2C%20Galle%2C%20Sri%20Lanka&output=embed",
  },
  whatsapp: {
    number: "94771234567",
    defaultMessage: "Hello, I would like to enquire about a stay at Kahanda Cove.",
    ariaLabel: "Start a WhatsApp chat with Kahanda Cove",
  },
  labels: {
    themeToggleLabel: "Switch color theme",
    menuLabel: "Open navigation menu",
    closeMenuLabel: "Close navigation menu",
    footerHeading: "Kahanda Cove",
    footerDescription: "A slow, private stay on Sri Lanka's southern coast.",
    addressLabel: "Find us",
    hoursLabel: "Reservations",
    copyright: "Kahanda Cove. Demo site.",
    roomsEyebrow: "Stay your way",
    roomsTitle: "Rooms made for slow mornings",
    roomsRateSuffix: "per night",
    availabilityTitle: "Plan your stay",
    checkInLabel: "Check-in",
    checkOutLabel: "Check-out",
    guestsLabel: "Guests",
    roomLabel: "Room preference",
    roomPlaceholder: "Choose a room",
    enquiryNameLabel: "Full name",
    enquiryPhoneLabel: "Phone number",
    enquirySubmitLabel: "Send availability enquiry",
    directBookingMessage: "Book direct, skip the commission.",
    attractionsEyebrow: "Beyond the villa",
    attractionsTitle: "The south at your pace",
    confirmationTitle: "Your availability enquiry is in",
    confirmationReference: "Your stay reference is {reference}.",
    confirmationWhatsAppLabel: "Send enquiry on WhatsApp",
    printVoucherLabel: "Print stay voucher",
    currencyLabel: "Display currency",
    indicativeRateLabel: "Indicative conversion. Your final rate is confirmed in LKR.",
  },
  bookingReferencePrefix: "KCV",
} satisfies HotelConfig;
